### ISSUE TITLE
[Multi] Database tasks

### ISSUE THREAD

**Issue by dvdblk** [uzh-eth-mp/app#4]
For tracking improvements / features needed for the database (sql and python code included)

## Todo
- [x] Verify that the data schema for `internal_transaction_data` is correct. 
  * Need to connect to a node with `--trace=on` and [find out how](https://ethereum.stackexchange.com/questions/3417/how-to-get-contract-internal-transactions
) the data looks like
- [x] All inserts in ([src/data_collection/app/db/manager.py](src/data_collection/app/db/manager.py) ) should be changed to upserts or `INSERT ... ON CONFLICT DO NOTHING`
  * repeated insertions of the same data might occur when the app is not exited properly (so only some transactions from a block get stored into the database). For instance a hypothetical scenario that fails as of now: app exits while only half of the transactions in a kafka message queue get inserted into the db, rest of the data in kafka gets wiped out, app restart will throw an error on reinsert of the same transactions.
- [x] ~~Create `block_processing_state` in [src/db/sql/00-block-transaction.sql](src/db/sql/00-block-transaction.sql)~~
- [x] #5
- [x] ~~Add get_block_transactions in db/manager.py~~
  * The get_block_transactions method should return a list of transaction hashes for a given block number (passed as an argument to the method)
  * Need to add three tests to tests/db/test_manager.py:
    1. Test getting multiple transactions for a single block number
    2. Test getting an empty list for a block number that doesn't exist
    3. Test getting an empty list for a block number that doesn't have any transactions
  * https://magicstack.github.io/asyncpg/current/api/index.html?highlight=fetch#asyncpg.connection.Connection.fetch
