### ISSUE TITLE
[Multi] Web3 tasks

### ISSUE THREAD

**Issue by dvdblk** [uzh-eth-mp/app#6]
For tracking improvements / features needed for the web3 code (producer and consumer)

## Todo
- [x] #7
  * Decide if we need a separate function for computing the block reward (e.g. `compute_block_reward` in the `app/node` directory OR if calling `trace_block` on a node is sufficient.
- [x] #14
  *  e.g. [**USDT** on ethereum](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7) and [**BUSD** on bsc](https://bscscan.com/token/0xe9e7cea3dedca5984780bafc599bd69add087d56)
- [x] #12
- [x] ERC1155 missing decimals, total_supply, name, symbol 
  * What should we do with this?
- [x] Add processing of internal transactions to `consumer.py`
- [x] #15
- [x] Check if BSC and ETC work properly even with the new NodeConnector headers
- [x] #13
  * After processing the first transaction, add an idle timer that will exit the consumer successfully after some time.
- [x] KafkaProducerManager should determine the number of partitions automatically
  * replace constant (`n_partitions`) with a function
